### ISSUE TITLE
How to  create an XMLTV object using the file data

### ISSUE THREAD

**Issue by tbrek** [Rubenfer/XMLTV#1]
Hi. I'm trying to use your package in my own app but I'm stuck on creating XMLTV object from xml file. Can you help?

**Comment by Rubenfer** [comment]
Hi Tom,
you should create an instance of XMLTV passing the xml file as data as argument.
You can find an example in [this test file](https://github.com/Rubenfer/XMLTV/blob/master/Tests/XMLTVTests/XMLTVTests.swift).

Then you can use _getChannels_ and _getPrograms_ methods.
```swift
public class XMLTV {
    public init(data: Data) throws
    public func getChannels() -> [TVChannel]
    public func getPrograms(channel: TVChannel) -> [TVProgram]
}
```

**Comment by tbrek** [comment]
@Rubenfer Awesome. Thanks. All sorted.
